#!/bin/bash

# EaglerProxy Interactive Setup Script
# This script will guide you through the configuration and setup process

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print functions
print_header() {
    echo -e "${BLUE}================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}================================${NC}"
}

print_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to ask yes/no questions
ask_yes_no() {
    local prompt="$1"
    local default="${2:-n}"
    local response
    
    if [ "$default" = "y" ]; then
        prompt="$prompt [Y/n]: "
    else
        prompt="$prompt [y/N]: "
    fi
    
    read -p "$prompt" response
    response=${response,,} # Convert to lowercase
    
    if [ -z "$response" ]; then
        response=$default
    fi
    
    [[ "$response" =~ ^(yes|y)$ ]]
}

# Function to ask for input with default value
ask_input() {
    local prompt="$1"
    local default="$2"
    local response
    
    if [ -n "$default" ]; then
        read -p "$prompt [$default]: " response
        echo "${response:-$default}"
    else
        read -p "$prompt: " response
        echo "$response"
    fi
}

# Check if Docker is installed
check_docker() {
    if ! command -v docker &> /dev/null; then
        print_error "Docker is not installed. Please install Docker first."
        echo "Visit: https://docs.docker.com/get-docker/"
        exit 1
    fi
    
    if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
        print_error "Docker Compose is not installed. Please install Docker Compose first."
        echo "Visit: https://docs.docker.com/compose/install/"
        exit 1
    fi
    
    print_info "Docker and Docker Compose are installed ✓"
}

# Check if .env file exists
check_env_file() {
    if [ -f ".env" ]; then
        print_warning ".env file already exists."
        if ask_yes_no "Do you want to overwrite it?" "n"; then
            return 0
        else
            print_info "Using existing .env file. You can edit it manually if needed."
            return 1
        fi
    fi
    return 0
}

# Create .env file from user input
create_env_file() {
    print_header "EaglerProxy Configuration"
    
    echo ""
    print_info "Let's configure your EaglerProxy instance."
    echo ""
    
    # Basic Configuration
    echo -e "${YELLOW}=== Basic Configuration ===${NC}"
    ADAPTER_NAME=$(ask_input "Proxy name" "EaglerProxy")
    BIND_HOST=$(ask_input "Bind host (0.0.0.0 for all interfaces)" "0.0.0.0")
    BIND_PORT=$(ask_input "Bind port (port clients will connect to)" "8080")
    MAX_CONCURRENT_CLIENTS=$(ask_input "Maximum concurrent clients" "20")
    
    echo ""
    echo -e "${YELLOW}=== Performance Configuration ===${NC}"
    if ask_yes_no "Use native modules for better performance? (Requires build tools)" "y"; then
        USE_NATIVES="true"
    else
        USE_NATIVES="false"
        print_warning "Native modules disabled. Performance may be reduced."
    fi
    
    echo ""
    echo -e "${YELLOW}=== Default Server Configuration ===${NC}"
    SERVER_HOST=$(ask_input "Default Minecraft server host" "127.0.0.1")
    SERVER_PORT=$(ask_input "Default Minecraft server port" "1111")
    
    echo ""
    echo -e "${YELLOW}=== EagProxyAAS Plugin Configuration ===${NC}"
    EAGPROXYAAS_INTERNAL_PORT=$(ask_input "Internal server port" "25569")
    EAGPROXYAAS_INTERNAL_IP=$(ask_input "Internal server IP" "127.0.0.1")
    
    if ask_yes_no "Allow clients to specify custom ports?" "y"; then
        ALLOW_CUSTOM_PORTS="true"
    else
        ALLOW_CUSTOM_PORTS="false"
    fi
    
    if ask_yes_no "Allow direct connect endpoints?" "y"; then
        ALLOW_DIRECT_CONNECT="true"
    else
        ALLOW_DIRECT_CONNECT="false"
    fi
    
    if ask_yes_no "Disallow connections to Hypixel?" "n"; then
        DISALLOW_HYPIXEL="true"
    else
        DISALLOW_HYPIXEL="false"
    fi
    
    if ask_yes_no "Show disclaimers to clients?" "n"; then
        SHOW_DISCLAIMERS="true"
    else
        SHOW_DISCLAIMERS="false"
    fi
    
    echo ""
    echo -e "${YELLOW}=== Authentication Configuration ===${NC}"
    if ask_yes_no "Enable authentication?" "n"; then
        AUTH_ENABLED="true"
        AUTH_PASSWORD=$(ask_input "Authentication password" "")
    else
        AUTH_ENABLED="false"
        AUTH_PASSWORD=""
    fi
    
    # Write .env file
    cat > .env << EOF
# EaglerProxy Configuration
# Generated by setup.sh on $(date)

# ===== Adapter Configuration =====
ADAPTER_NAME=$ADAPTER_NAME
BIND_HOST=$BIND_HOST
BIND_PORT=$BIND_PORT
MAX_CONCURRENT_CLIENTS=$MAX_CONCURRENT_CLIENTS
USE_NATIVES=$USE_NATIVES

# ===== Target Server Configuration =====
SERVER_HOST=$SERVER_HOST
SERVER_PORT=$SERVER_PORT

# ===== EagProxyAAS Plugin Configuration =====
EAGPROXYAAS_INTERNAL_PORT=$EAGPROXYAAS_INTERNAL_PORT
EAGPROXYAAS_INTERNAL_IP=$EAGPROXYAAS_INTERNAL_IP
ALLOW_CUSTOM_PORTS=$ALLOW_CUSTOM_PORTS
ALLOW_DIRECT_CONNECT=$ALLOW_DIRECT_CONNECT
DISALLOW_HYPIXEL=$DISALLOW_HYPIXEL
SHOW_DISCLAIMERS=$SHOW_DISCLAIMERS

# ===== Authentication Configuration =====
AUTH_ENABLED=$AUTH_ENABLED
AUTH_PASSWORD=$AUTH_PASSWORD
EOF
    
    print_info ".env file created successfully ✓"
}

# Start the proxy
start_proxy() {
    print_header "Starting EaglerProxy"
    
    print_info "Building Docker image..."
    if docker compose version &> /dev/null; then
        docker compose build
    else
        docker-compose build
    fi
    
    print_info "Starting containers..."
    if docker compose version &> /dev/null; then
        docker compose up -d
    else
        docker-compose up -d
    fi
    
    echo ""
    print_info "EaglerProxy is now running! ✓"
    echo ""
    echo -e "${GREEN}Access your proxy at:${NC} ws://${BIND_HOST}:${BIND_PORT}"
    echo ""
    echo -e "${YELLOW}Useful commands:${NC}"
    echo "  - View logs: docker compose logs -f eaglerproxy"
    echo "  - Stop proxy: docker compose stop"
    echo "  - Start proxy: docker compose start"
    echo "  - Restart proxy: docker compose restart"
    echo "  - Remove containers: docker compose down"
    echo ""
}

# Main script
main() {
    print_header "EaglerProxy Setup Script"
    
    echo ""
    print_info "This script will help you set up and run EaglerProxy in a Docker container."
    echo ""
    
    # Check prerequisites
    check_docker
    
    echo ""
    
    # Configure .env file
    if check_env_file; then
        create_env_file
    fi
    
    # Load .env file safely
    if [ -f ".env" ]; then
        set -a
        source .env
        set +a
    fi
    
    echo ""
    
    # Ask if user wants to start now
    if ask_yes_no "Do you want to start EaglerProxy now?" "y"; then
        start_proxy
    else
        print_info "Configuration saved. You can start the proxy later with: docker compose up -d"
    fi
    
    echo ""
    print_header "Setup Complete"
}

# Run main function
main || exit $?
